### ISSUE TITLE
Nothing ear (2024) won't connect

### ISSUE THREAD

**Issue by TheDocHudson** [radiance-project/ear-web#72]
I'm on windows 11, latest build, running Google Chrome.

It will connect to the headphones via a serial port connection. I select the headphones, but nothing changes in the interface. It still shows up as the "connect a device" screen, no matter how many times I attempt to connect.

I only have my nothing ear connected, no other external audio devices of any kind.
The headphones stream audio from my pc perfectly fine, so I don't see why it won't connect in the app.

**Comment by Lisra-git** [comment]
Hey
Can you send the serial of your device? Did you have earbuds replaced?

**Comment by TheDocHudson** [comment]
> Hey Can you send the serial of your device? Did you have earbuds replaced?

Hey, funny you ask that. I did! The serial ID is written on the case lid, right? In that case, it's:
**SH10622413000254**

**Comment by Lisra-git** [comment]
Yeah then the issue is due to the replacement, for some reason this cause the serial to be hidden in the software, I'm working on an alternative solution but for the moment there's nothing to be done :/

**Comment by TheDocHudson** [comment]
My guess would be is that they hide the new SN to stop users from having "unlimited support."
If you have a clean SN to report, then you can continuously report new issues with earbuds you only paid once for, even if they were recently replaced.

Perhaps make the program not check for a SN? Not sure what goes on behind closed curtains, but I suspect you could just assume users won't attempt to use other headphones with this tool??

**Comment by Lisra-git** [comment]
Hey
This should now be working, please have a look

**Comment by andreiandrocj16** [comment]
hello, this still doesnt work for me, i have not replaced any earbuds whatsoever, i keep having the same issue. Thanks
