### ISSUE TITLE
CMF BUDS wont connect

### ISSUE THREAD

**Issue by hach-ship** [radiance-project/ear-web#73]
CMF BUDS wont connect

**Comment by Lisra-git** [comment]
Hey
Did you solve the issue?

**Comment by VojtaTaptuch** [comment]
Hi, got the same issue CMF Buds 2 Plus

**Comment by Lisra-git** [comment]
> Hi, got the same issue CMF Buds 2 Plus

Hey
What's the serial number and colour

**Comment by VojtaTaptuch** [comment]
> > Hi, got the same issue CMF Buds 2 Plus
> 
> Hey What's the serial number and colour

So my SN is 1351052514001506 in color white

**Comment by Lisra-git** [comment]
Hey
It should already be working, can you describe the issue and check browser console (F12)

**Comment by VojtaTaptuch** [comment]
> Hey It should already be working, can you describe the issue and check browser console (F12)

Sure, 
so after selecting CMF buds in the popup and clicking the connect button nothing happens - Here is the error from the console

<img width="548" height="151" alt="Image" src="https://github.com/user-attachments/assets/9cb2348d-1300-4c33-8b00-d6c079071797" />

**Comment by Lisra-git** [comment]
Hey
This error is related to your PC directly
Try to close all tabs and try again

**Comment by VojtaTaptuch** [comment]
Hi again, 
so yeah the problem was with my PC (bluetooth dongle), fix it and now its working!
Thanks a lot for the help

**Comment by Yavuz-Kagan-Yadigar** [comment]
> Hi again, 
> so yeah the problem was with my PC (bluetooth dongle), fix it and now its working!
> Thanks a lot for the help
 How did you solve it?

**Comment by VojtaTaptuch** [comment]
> > Hi again,
> > so yeah the problem was with my PC (bluetooth dongle), fix it and now its working!
> > Thanks a lot for the help
> > How did you solve it?

A long time ago I disabled this bluetooth device in device manager bcs some handsfree issues (don't really remember) -> Enebled this again and the problem was fixed

<img width="256" height="21" alt="Image" src="https://github.com/user-attachments/assets/80b5f35b-464c-4102-8de6-bf66ca4f4c0b" />

**Comment by Yavuz-Kagan-Yadigar** [comment]
> > > Hi again,
> > > so yeah the problem was with my PC (bluetooth dongle), fix it and now its working!
> > > Thanks a lot for the help
> > > How did you solve it?
> 
> A long time ago I disabled this bluetooth device in device manager bcs some hand free issues (don't really remember) -> Enebled this again and the problem was fixed
> 
> <img alt="Image" width="256" height="21" src="https://private-user-images.githubusercontent.com/78140978/481379138-80b5f35b-464c-4102-8de6-bf66ca4f4c0b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYwNjQzMTMsIm5iZiI6MTc1NjA2NDAxMywicGF0aCI6Ii83ODE0MDk3OC80ODEzNzkxMzgtODBiNWYzNWItNDY0Yy00MTAyLThkZTYtYmY2NmNhNGY0YzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI0VDE5MzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOGZiOTg5MzQ4ZTlhMTgyZDk0MzRlNzAxNzIwOWVkODI4NTEzZmIyZWY2OTYyMThkOGY4MGZhMzk5Mjk5OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S2EMQNKwwGCuyWp74iknCNaG9cVa_y2yIK2XjsDAs7c">

Oh, thank you. It's already enabled for me, but still not works.

**Comment by Lisra-git** [comment]
Hey
Since this is not directly related to the project, I'll have to close this issue, hopefully you found a fix!
